== Einleitung

Seit 2500 Jahren werden Informationen in Schrift, Bild oder jeglichem geeigneten Objekt versteckt.
Diese Technik wird als Steganografie bezeichnet.
Der Begriff leitet sich vom griechischen _steganós (στεγανός)_ und _-graphia (γραφή)_ ab, was grob übersetzt für _verborgen_ und _Schrift_ steht. cite:[gemoll_griechisch-deutsches_nodate]
Inzwischen wird im wissenschaftlichen Umfeld oft die Abkürzung _Stego_ verwendet.

Im fünften Jahrhundert nutzten die Griechen im Krieg gegen Persien diese Technik, um die Einnahme durch die Perser zu verhindern.
Die schottische Königin Mary griff im 16. Jahrhundert auf Kryptografie und Steganografie zurück, um ihre Briefe vor ungewünschten Lesern zu schützen.
Im Jahr 1499 veröffentlichte der deutsche Abt Johannes Trithemius sein Werk _Steganographia_, in welchem er sich erstmals, soweit bekannt, mit Methoden zum Verstecken von Nachrichten in Schrift systematisch beschäftigte. cite:[singh_code_2000]

Insbesondere mit der Entwicklung von Computern nahm Steganografie als Forschungsbereich final Einzug in die Wissenschaft.
Großes Interesse kam besonders bei der Einbettung von Informationen in Medien wie Bild- und Audiodaten auf.
Die Grundlagen der noch heute relevanten Methoden wurden bereits in den 1990er bis 2000er Jahren entwickelt und werden in den kommenden Kapiteln dieser Arbeit genauer vorgestellt.
Neben den steganografischen Verfahren wird auch auf Methoden aus dem Information Hiding eingegangen, welches neben Steganografie, Wasserzeichen sowie die Einbettung von Daten in Strukturelementen von Trägermedien einschließt.

[#motivation]
=== Motivation

Für Entwickler von Schadsoftware, auch bekannt als Malware, ist es wichtig, im Wettstreit mit den Gesetzeshütern einen Schritt voraus zu sein.
Dazu wird inzwischen die Technik der Steganografie immer öfter aufgegriffen.
Sogenannte Payloads mit weiterem Schadcode für Multi-Layer-Malware oder Befehle für Command-and-Control-Malware (kurz C&C) können damit in das von der Schadsoftware befallene System eingeschleust werden.
Gestohlene Daten wie Passwörter aus dem System können ebenso in Trägermedien eingebettet und ausgeschleust werden, ohne bei IT-Sicherheitssystem wie Firewalls oder Antivirenprogrammen aufzufallen.
Die genannten Vorgänge sind jeweils als Dateninfiltration und Datenexfiltration bekannt. cite:[benson_ryan_data_nodate,benson_ryan_data_nodate-1]

Die Verwendung von Steganografie in Bilddateien kann bereits in vielen Fällen erkannt werden.
Jedoch folgt darauf meist keine genauere Zuordnung zu einem bestimmten Algorithmus, einer möglicherweise verwendeten Bibliothek zur Verarbeitung von Bilddaten oder sogar einer bestimmten Malware oder Malware-Familie.
Ein solches Fingerprinting kann vielfältige Informationen zum Angriffshergang, Beschaffenheit und Ursprung der Malware wie auch zur Herkunft der damit operierenden Täter liefern.
Dies kann für die strafrechtliche Verfolgung von großer Bedeutung sein.

Neben der Verwendung durch Malware wird Steganografie für das Einbetten von digitalen Wasserzeichen genutzt.
Bilddateien werden hierbei mit einem sichtbaren oder versteckten Code versehen werden, um ungewünschte Distributionen oder Manipulationen des Bildes nachverfolgen zu können.
So können Urheberrechte geschützt und deren Bruch durch beispielsweise Piraterie geahndet werden.
Die Analyse von potenziell mit Wasserzeichen gekennzeichneten Bildern kann also wie bei Malware Aufschluss auf Herkunft und konkrete Art der Einbettung liefern.
Die Robustheit des verwendeten Algorithmus kann auf diese Weise getestet werden.
Außerdem muss gewährleistet werden, dass bei der Einbettung keine privaten Informationen preisgegeben werden. cite:[dittmann_motivation_2000]

Aus dieser Motivation heraus wurden im Rahmen der Erstellung des Exposés zu dieser Arbeit unter anderem die folgenden Forschungsaspekte identifiziert:

- Literatur-Recherche von aktuellen und relevanten Information Hiding Verfahren
- Literatur-Recherche zur Identifikation potenziell geeigneter Ansätze zur Eigenschaftsbestimmung
- Erstellung und Dokumentation eines Merkmalssets zur Evaluation
- Experimentelle Untersuchung des Vorhandenseins dieser Merkmale in Testdatensets

Daraus ergeben sich die im nächsten Abschnitt vorgestellten Ziele dieser Arbeit.

[#zielsetzung]
=== Zielsetzung

Die Zielstellung dieser Arbeit konzentriert sich auf die folgenden Punkte:

. Erstellung einer Liste von Malware-Vorkommnissen, in denen Steganografie mit Bildern als Trägermedium verwendet wurde
. Erstellung einer Auswahlliste an Stego-Software, die vergleichbar in ihrer Funktionalität zu den gefundenen Schadprogrammen sind, sowie einer Auswahlliste an Wasserzeichen-Software
. Recherche und/oder Aufbau von Forschungsdaten aus Cover- und Stego-Bildpaaren
. Entwicklung eines Prototyps eines Werkzeugs zur Identifikation von Merkmalen für den Einsatz bestimmter Stego-Verfahren

Durch das Erreichen der genannten Ziele soll ein erster Ansatz zum Fingerprinting von Stego-Tools basierend auf deren verwendeten Bilder erarbeitet werden.
Der Prototyp soll für den Einsatz mit Malware als auch mit Wasserzeichen weiter ausbaubar sein, wobei dies nicht mehr im Fokus dieser Arbeit liegt.

Da die Menge der Malware-Vorkommnissen erwartbar weit größer als die Menge an Stego- und Wasserzeichen-Tools sein dürfte, werden die Malware-Vorkommnisse nur mittels Literaturrecherche untersucht, während die Tools auch praktisch durch Tests ausgewertet.

Die beschriebene Ziele werden fortan im Rahmen dieser Arbeit als **Z.1** bis **Z.4** referenziert.

<<<

[#forschungsfragen-hypthosen]
=== Forschungsfragen und Hypothesen

Aus der Zielsetzung lassen sich folgende Forschungsfragen und zugehörigen Hypothesen ableiten:

[quanda]
Frage: Können Werkzeuge zur Einbettung von Daten mittels Steganografie nur anhand ihrer Ausgabebilder und der Originalbilder automatisiert identifiziert werden?::
*Hypothese*: Ja, es lassen sich immer wiederkehrende Merkmale in den Bildern nachweisen, die mit dem verwendeten Einbettungswerkzeug in Zusammenhang stehen.

Frage: Gibt es eine Schnittmenge bzgl. der Eigenschaften der verwendeten Stego-Algorithmen und technischen Umsetzung zwischen Malware, Stego- und Wasserzeichen-Tools?::
*Hypthese*: Ja, es kann eine Schnittmenge zumindest in der Kategorie der Stego-Algorithmen und der zur Umsetzung verwendeten Programmiersprachen und Bibliotheken abgesteckt werden.

Frage: In welchen Eigenschaften unterscheiden sich die drei Kategorien?::
*Hypothese*: Bei Malware liegt ein größerer Wert auf Performance als auf Robustheit, während Wasserzeichen-Tools umgekehrt gewichtet sind.
Stego-Tools sind je nach Gewichtung der Entwickler aufgestellt.

Die beschriebenen Fragen werden fortan im Rahmen dieser Arbeit als **F.1** bis **F.3** referenziert.

=== Aufbau der Arbeit

Im <<theoretische-grundlagen,folgenden Kapitel>> werden die theoretischen Grundlagen kurz dargelegt.
Da im Rahmen dieser Arbeit keine eigenen steganografischen Algorithmen entwickelt werden, wird nicht tiefergehend auf die mathematische Basis eingegangen.
Im Kapitel <<methodik,Methodik>> werden das Vorgehen zur Erreichung von *Z.1* bis *Z.4* dokumentiert.
Das Kapitel <<ergebnisse,Ergebnisse>> stellt die gesammelten Ergebnisse mithilfe von Grafiken und Code-Ausschnitten vor.
Die Kapitel <<schlussfolgerung,Zusammenfassung>> und <<ausblick,Ausblick>> geben schließlich einen kurzen Rückblick auf die Arbeit und zeigen weitere Ausbaumöglichkeiten des entwickelten Programmcodes sowie Richtungen zur Forschung auf.