[#ausblick]
== Ausblick

Der folgende Ausblick geht zunächst auf allgemeine Anknüpfungspunkte zu dieser Arbeit ein.
Danach werden in weiteren Abschnitten Ausbau- und Verbesserungsmöglichkeiten des Forschungsdatensatzes und des Detektors vorgestellt.

[#ausblick-allgemein]
=== Allgemein

In dieser Arbeit wurden drei grundlegende Merkmalsräume untersucht.
Diese wurden spezifisch für die untersuchten Stego-Apps ausgewählt und führten auch zu spezifischen Ergebnisse.
Allerdings sind nicht nur die zu untersuchenden Stego-Tools relevant für die Merkmalssuche, sondern auch der verwendete Datensatz.
Der gewählte Datensatz wies keine Metadaten oder sonstige spezifische Eigenschaften von bestimmten Kameras auf, die zum Beispiel Rückschlüsse auf den Benutzer des Stego-Tools oder eine Lokalisation der Bilderstellung zugelassen hätten.
Mit derartigen Daten, die ein Kamera-Fingerprinting ermöglichen, könnte neben dem verwendeten Tool auch Erkenntnisse über den Anwender des Tools gesammelt werden.
Eine weitere Möglichkeit dazu ist die Verwendung von künstlicher Intelligenz zur Erkennung von Sprache in extrahierten Payloads.
So hätte im Datensatz dieser Arbeit festgestellt werden können, dass englische Texte eingebettet wurden.
Mit den modernen großen Sprachmodellen (LLMs) könnte versucht werden, sogar zu erkennen, dass es sich um Werke von Shakespear handelt.
In diesem Beispiel würde dies darauf hindeuten, dass der Anwender des Tools ein Liebhaber klassischer englischer Literatur ist und somit womöglich aus dem englischsprachigen Raum stammt oder sich dort schon lange aufhält.
Bei Payloads aus Malware könnte dagegen die verwendete Programmiersprache und möglicherweise besondere Zeichen aus nicht-lateinischen Alphabeten erkannt werden, die ebenfalls auf die Herkunft der Entwickler der Malware schließen lassen könnten.
Bei einer solchen Herangehensweise ist jedoch zu bedenken, dass zukünftige Abwehrmechanismen gegen diese Erkennungen bewusst falsche Fährten legen könnten.

[#ausblick-forschungsdatensatz]
=== Forschungsdatensatz

Der Forschungsdatensatz ließe sich vielfältig erweitern, um weitere Untersuchungen zu ermöglichen.
Die folgende Liste stellt einige mögliche Erweiterungspunkte vor.

.Liste möglicher Erweiterungen des Forschungssatzes
. *Diversere Einbettungsnachrichten*: Zum Beispiel wurden nur Texte aus dem Englischen eingebettet.
Womöglich würden nicht-lateinische Sprachen jedoch zu erkennbaren Mustern auf der LSB-Ebene führen.
Ebenso könnte eingebetteter Programmcode durch die Wiederholung von Schlüsselworten eine Mustererkennung erlauben oder die Dateigröße der Stego-Bilder berechenbar verändern.

. *Diversere Stego-Tools*: Diversere Stego-Tools könnten zu weiteren übergreifenden Erkenntnissen im Forschungsgebiet des Information Hidings führen.

. *Größere Bildvielfalt*: Die untersuchten Bildpaare waren in den Grauton konvertiert.
Sowohl für die Stego-Verfahren in der Raum- als auch in der Frequenz-Domäne sind die Farbkanäle für die Einbettung von Belang.
Farbige Bilder mit unterschiedlichen Werten im Alpha-Kanal könnten ebenfalls neue Merkmale liefern.

[#ausblick-detektor]
=== Detektor

Nachfolgend werden offenen Punkte des Detektors gelistet.
Diese weiteren Features und Optimierungen könnten in einer weiteren Ausbaustufe umgesetzt sein.

.Liste der offenen Punkte des Detektors
. *Gewichtung der Regeln*: Im Rahmen dieser Arbeit wurde auf eine komplexe Gewichtung der Ergebnisse von Regeln verzichtet, da dazu jede einzelne Regel statistisch hätte ausgewertet und verglichen werden müssen.
Dies sollte bei einem weiteren Ausbau vorgenommen werden, um bessere Ergebnisse bei der Erkennung der Stego-Tools zu erreichen.
Eine Herangehensweise ist, jeder der vorgestellten Regeln einzeln mit dem Datensatz und den Metriken aus <<ergebnisse-detektor-auswertung>> zu evaluieren und alle Ergebnisse miteinander zu vergleichen.
Dann ist eine Gewichtungsskala zu wählen, wie zum Beispiel 1 bis Anzahl der Regeln _n_.
Die erfolgreichste/n Regel/n erhält/erhalten die höchste Gewichtung und die anderen entsprechend ihres Rangs in der Ergebnisliste eine niedrigere.

. *Mehrere Unterbindungen in einer Regel*: Der aktuelle Aufbau der Regelstruktur wurde so vorgenommen, dass eine Regel immer einen Fall prüft.
In der Praxis stellte sich aber heraus, dass es durchaus sinnvoll sein könnte, in einer Regel mehrere Unterbindungen prüfen zu können und so auch eine Unterbindung einem Tool zuweisen zu können.
Auf diese Weise würde sich die aktuelle Duplizieren der Regeln deutlich verringern lassen.

. *Auslagern von Regeln*: Es könnte sich auch als sinnvoll erweisen, die Regeln in einem flachen `rules`-Block zu definieren und dann nur per ID in einem Regelbaum zu referenzieren.
Dies würde ebenfalls die Duplizieren von Regeln deutlich verringern und zudem den Regelbaum deutlich einfacher erweiterbar machen.

. *Verwendung von YARA*: Anstelle der Verbesserung des bestehenden Detektors könnte die Umsetzung der Regeln mittels YARA angestrebt werden.
So würde eine Verknüpfung mit einem bestehenden Standard aufgebaut würde und es könnte in den Regeln auf Funktionalität von YARA zurückgriffen werden.
Aus Gründen der Komplexität der Erweiterung des YARA-Scanners wurde auf die Umsetzung des Detektors mittels YARA verzichtet.

. *Automatische Generierung von Regeln*: Sowohl die YAML-basierte aktuelle Variante als auch YARA-Regeln könnten automatisiert mittels Python generiert werden.
Dadurch würden sich mögliche Funde von Merkmalen schneller testen lassen.
